#!/bin/bash
# To pass options options to libsnark Makefile, put them in env var LIBSNARK_FLAGS.
# To clone libsnark from an alternate location, set env var LIBSNARK_SRC. For example:
#  LIBSNARK_SRC="$HOME/libsnark.git --branch master" ./get-libsnark
# To use curve BN128 instead of BN128 (which is x64-only), use:
#  CURVE=BN128 ./get-libsnark
# and pass CURVE=BN128 as an argument to make.

set -e

LIBSNARK_SRC=${LIBSNARK_SRC:-https://github.com/scipr-lab/libsnark}

CURVE=${CURVE:-ALT_BN128}

LIBSNARK_FLAGS="$LIBSNARK_FLAGS -DWITH_SUPERCOP=OFF -DCURVE=$CURVE"
if [[ `uname -s` == "Darwin" ]]; then
    LIBSNARK_FLAGS="$LIBSNARK_FLAGS -DWITH_PROCPS=OFF"
fi

set -x

DEPSRC=./depsrc
DEPINST=./depinst

mkdir -p $DEPINST
DEPINST=`pwd -P`/$DEPINST  # remember absolute path

mkdir -p $DEPSRC
cd $DEPSRC

[ ! -d libsnark ] && git clone $LIBSNARK_SRC libsnark
cd libsnark
git pull
git checkout cmake
git submodule init && git submodule update

mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$DEPINST $LIBSNARK_FLAGS ..
make clean
make snark
make install
