#!/bin/bash
# To pass options options to libsnark Makefile, put them in env var LIBSNARK_FLAGS.
# To clone libsnark from an alternate location, set env var LIBSNARK_SRC. For example:
#  LIBSNARK_SRC="$HOME/libsnark.git --branch master" ./get-libsnark

set -e

LIBSNARK_FLAGS="$LIBSNARK_FLAGS NO_SUPERCOP=1 NO_GTEST=1 NO_DOCS=1"
if [[ `uname -s` == "Darwin" ]]; then
    LIBSNARK_FLAGS="$LIBSNARK_FLAGS NO_PROCPS=1"
fi

LIBSNARK_SRC=${LIBSNARK_SRC:-https://github.com/scipr-lab/libsnark}

set -x

DEPSRC=./depsrc
DEPINST=./depinst

mkdir -p $DEPINST
DEPINST=`pwd -P`/$DEPINST  # remember absolute path

mkdir -p $DEPSRC
cd $DEPSRC

[ ! -d libsnark ] && git clone $LIBSNARK_SRC libsnark
cd libsnark
git pull
# TODO: submit -fPIC patch to ate-pairing
INC_DIR=-fPIC ./prepare-depends.sh
make clean
make lib $LIBSNARK_FLAGS
make install PREFIX=$DEPINST $LIBSNARK_FLAGS
